### ISSUE TITLE
Variables in Detection Method

### ISSUE THREAD

**Issue by aimar115** [asjimene/SCCM-Application-Packager#23]
Hello
Found out that it still not possible to use Variables in detection method.
Tested like that:
defined in DownloadVersionCheck
$FileVersion = "4.2.3.66"
running the script
Add-LogContent "$detMethodCommand"
Writes to log -ExpectedValue "$FileVersion"
Tried both:
$detMethodCommand += " -ExpectedValue "$($DetectionMethod.ExpectedValue)""
and
$detMethodCommand += " -ExpectedValue '$($DetectionMethod.ExpectedValue)'"
no difference.
same with that one also
$detMethodCommand += " -ExpectedValue $($DetectionMethod.ExpectedValue)"

can you help?

**Comment by asjimene** [comment]
This should be fixed in the commit [here](https://github.com/asjimene/SCCM-Application-Packager/commit/8c0e11b4a4090620e4a22d76cb920ac0140d758e )
Any instances of $Version or $FullVersion in detection methods and install/uninstall commands will be replaced with the actual version or FullVersion number. No need for the "`" anymore either!
